### ISSUE TITLE
Unable to use built in DinklyDataModel->update with models that do not use 'id' as primary key

### ISSUE THREAD

**Issue by smacewan101** [lewsid/dinkly#10]
This is easy enough to get around by overriding the call to update and adjusting the final line of the query build:
    <code>$query .= " where id='" . $this->Id . "'";</code>
on line 132 of DinklyDataModel to what you need. But just wanted to give you a heads up. Possibly allow specification of (compound) primary key in the config schema for the model?

**Comment by andrewvt** [comment]
This is addressed in my latest commit referenced above.  I fully tested it for even instances where the primary key is a field name with underscores and it works just as expected.  @lewsid - please review and close if you agree with this approach.
