### ISSUE TITLE
Cleanup $_SERVER['APPLICATION_ROOT'] and fix double slash

### ISSUE THREAD

**Issue by tetranz** [lewsid/dinkly#33]
I can do this or create a pull request if you like.

There are two issues with $_SERVER['APPLICATION_ROOT']. The first is mostly cosmetic I guess.

We have this in bootstrap.php.
`$_SERVER['APPLICATION_ROOT'] = dirname(__FILE__) . '/../';`
The resulting path ends in /config/../ and any calculated path contains /config/../ .
If nothing else, this just looks untidy when debugging.

I suggest changing it to
`$_SERVER['APPLICATION_ROOT'] = realpath(dirname(__FILE__) . '/..');`

That produces a simple clean path like `/var/apps/myapp` rather than `/var/apps/myapp/config/../`

The other issue is that `$_SERVER['APPLICATION_ROOT']` is used inconsistently in terms of whether or not a trailing slash is expected. In the many (most?) places, the appended path adds another slash so there are many places where the resulting path is calculated with a double slash like `/var/apps/myapp/config/..//somepath`. This seems to work but is untidy and I suspect might even be ambiguous on some file systems.

If we use my realpath suggestion above, we need to find all uses of `$_SERVER['APPLICATION_ROOT']` and make sure that a slash is added or alternatively make the bootstrap line this:
`$_SERVER['APPLICATION_ROOT'] = realpath(dirname(__FILE__) . '/..') . '/';`
and remove the slash from appended paths. Either way is okay but we should do one or the other.

**Comment by lewsid** [comment]
Good suggestion. Implemented in 3903aec.
