### ISSUE TITLE
Block any attempts to include ../ in the incoming URL

### ISSUE THREAD

**Issue by tetranz** [lewsid/dinkly#34]
The module name part of the URL causes a PHP controller file to be included. We should block any attempts to navigate around the file system by requesting a path with ../../ etc. It's probably a stretch because the filename needs to end in Controller.php but even so, it's an easy hole to patch in BaseDinkly::getContext. It could potentially be an issue if coupled with something like a careless image upload which allowed a PHP file to be uploaded.

**Comment by lewsid** [comment]
Fixed in 2113eef
