### ISSUE TITLE
initWith() not returning true if record has been found

### ISSUE THREAD

**Issue by DannySchick** [lewsid/dinkly#37]
In BaseDinklyDataModel.

Need to add a return true; after $this->hydrate() in the initWith function.

**Comment by andrewvt** [comment]
Typically the check for a result we use is if(!$this->deal->isNew()) for example.    $this->hydrate() does return true and since that is what initWith() returns it is odd that it wouldn't in turn return true as well.  Closing since isNew() works for the check for results.
