### ISSUE TITLE
Warning related to Dinkly -> filterFiles

### ISSUE THREAD

**Issue by bigSiebs** [lewsid/dinkly#50]
```PHP Warning:  Missing argument 1 for BaseDinkly::filterFiles(), called in /Users/joe/Dropbox (Bluehouse Group)/projects/path/classes/core/base/BaseDinkly.php on line 943 and defined in /Users/joe/Dropbox (Bluehouse Group)/projects/path/classes/core/base/BaseDinkly.php on line 736```

I think the argument should be removed from this function's signature. I don't see any indication that it should be passed something.

**Comment by lewsid** [comment]
Good catch, not sure what I had in mind there, but was just borrowing from the other filter functions.

**Comment by lewsid** [comment]
Fixed in 3.26
