### ISSUE TITLE
Get deprecation warning when running gen_module.php in PHP 7.2

### ISSUE THREAD

**Issue by bigSiebs** [lewsid/dinkly#52]
```PHP Deprecated:  Function create_function() is deprecated in /Users/joe/Dropbox (Bluehouse Group)/projects/path/classes/core/custom/Dinkly.php on line 597```

That's in a override of the convertToCamelCase in BaseDinkly. The overridden function would throw the same notice.

**Comment by lewsid** [comment]
Fixed in 3.34
